name: open_weather_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Get User Position
  geolocator: ^10.1.0

  intl: ^0.18.0

  # To manage user authentication
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_auth: ^4.15.3

  # look up for internet connection
  connectivity_plus: ^5.0.2

  # To Store Data In Local Storage
  shared_preferences: ^2.2.2

  # Make Pages Responsive To All Devices
  flutter_screenutil: ^5.9.0

  # Svg Image
  flutter_svg: ^2.0.9

  # Dependency Injection
  get_it: ^7.6.4

  # Fetch Data From Api
  dio: ^5.4.0

  # Logging Interceptor
  logging: ^1.2.0

  # BloC State Management
  flutter_bloc: ^8.1.3

  # Being able to compare objects in Dart
  equatable: ^2.0.5

  # Handle Success/Error State From Data Source
  either_dart: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
